sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tP2oZV9qeAiwxxHVnRM
    access-key-secret: C3n11MKcfReZZHKk5C5LQ3lrhBzBFC
    bucket-name:  sky-bao
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

